<?php
class Net_Top_Request_TradeFullinfoGet extends Net_Top_Request
{
}

Net_Top_Metadata::add(
    'TradeFullinfoGet',
    array(
        'parameters' => array(
            'required' => array(
                'fields',
                'tid',
            ),
        ),
        'fields' => array(
            ':all' => array(
                'seller_nick',
                'buyer_nick',
                'title',
                'type',
                'created',
                'sid',
                'tid',
                'seller_rate',
                'buyer_rate',
                'status',
                'payment',
                'discount_fee',
                'adjust_fee',
                'post_fee',
                'total_fee',
                'pay_time',
                'end_time',
                'modified',
                'consign_time',
                'buyer_obtain_point_fee',
                'point_fee',
                'real_point_fee',
                'received_payment',
                'commission_fee',
                'buyer_memo',
                'seller_memo',
                'alipay_no',
                'buyer_message',
                'pic_path',
                'iid',
                'num',
                'price',
                'buyer_alipay_no',
                'receiver_name',
                'receiver_state',
                'receiver_city',
                'receiver_distrinct',
                'receiver_address',
                'receiver_zip',
                'receiver_mobile',
                'receiver_phone',
                'buyer_email',
                'seller_alipay_no',
                'seller_mobile',
                'seller_phone',
                'seller_name',
                'seller_email',
                'available_confirm_fee',
                'has_postFee',
                'timeout_action_time',
                'snapshot_url',
                'cod_fee',
                'shipping_type',
                'orders',
                'orders.title',
                'orders.pic_path',
                'orders.price',
                'orders.num',
                'orders.iid',
                'orders.sku_id',
                'orders.refund_status',
                'orders.status',
                'orders.tid',
                'orders.total_fee',
                'orders.payment',
                'orders.discount_fee',
                'orders.adjust_fee',
                'orders.snapshot_url',
                'orders.timeout_action_time',
                'orders.sku_properties_name',
                'orders.item_meal_name',
            ),
        ),
        'api_type' => 'Trade',
        'method' => 'taobao.trade.fullinfo.get',
        'class' => 'Net_Top_Request_TradeFullinfoGet',
        'is_secure' => '1',
    )
);
